### ISSUE TITLE
java.lang.RuntimeException: Your content must have a ViewGroup whose id attribute is 'R.id.progress_container'

### ISSUE THREAD

**Issue by mitsus** [johnkil/Android-ProgressFragment#18]
Dear johnkil,
firstly compliments for great work.
I'm try to use your library (SherlockProgressFragment). I've follow your guide, but when i click for show fragment i've the error as issue title:

java.lang.RuntimeException: Your content must have a ViewGroup whose id attribute is 'R.id.progress_container'

I've include your fragment_custom_progress into my layout...where are my errors?

Thanks and Best Regards

**Comment by DevendraSingh91** [comment]
@johnkil  its same in Fragment.
